# SPDX-License-Identifier: MIT OR Apache-2.0
name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"   # publish only on version tags

# avoid duplicate publishes on rapid re-tags
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  # Fast sanity tests without liboqs
  tests:
    name: Mock tests (no liboqs)
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-mock-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --no-default-features --features kyber768,dilithium2

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-22.04
    needs: [tests]
    if: startsWith(github.ref, 'refs/tags/v')
    # OIDC for Trusted Publishing
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish (OIDC trusted)
        run: cargo publish --locked
